// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

// Prefer env vars (set by Lovable Cloud). Fallbacks prevent a blank screen if env injection fails.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "https://fhaisuzqkqdupmrfeldd.supabase.co";

const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoYWlzdXpxa3FkdXBtcmZlbGRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY1NjkwMTMsImV4cCI6MjA4MjE0NTAxM30.VwFj_iwky6efO84Ne-B7BZAbsvfovJ_gvwJhQju8e8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
